[package]
name = "app"
version = "0.1.0"
description = "Aplicación Cuentas Claras"
authors = [
    "Victor Farias",
    "Carlos Bisgono",
    "Rosa Ramirez",
    "Alejandra Mármol",
    "Ricardo Garcia",
    "Rossana Ilardo"


]
license = "Apache-2.0"
repository = "https://github.com/CI3715/Grupo2_LimitTokenReached"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
# Framework ejecutable Tauri (Heredado del workspace)
tauri = { workspace = true }

# Inclusión de los crates internos del workspace
dominio = { workspace = true }
aplicacion = { workspace = true }
infraestructura = { workspace = true }
contrato = { workspace = true }

# Utilidades de serialización, errores y logs (Heredadas del workspace)
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = "0.4"
tauri-plugin-log = "2"
