openapi: 3.1.0
info:
  title: Cuentas Claras - Servidor
  version: 0.1.0
paths:
  /ping:
    get:
      summary: Connection
      operationId: connection_ping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
