openapi: 3.1.0
info:
  title: Cuentas Claras - Servidor
  version: 0.1.0
paths:
  /ping:
    get:
      summary: Ping
      operationId: ping_ping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingRespuesta'
components:
  schemas:
    PingRespuesta:
      properties:
        estado:
          type: string
          title: Estado
        mensaje:
          type: string
          title: Mensaje
        version:
          type: string
          title: Version
        timestamp:
          type: string
          title: Timestamp
      type: object
      required:
      - estado
      - mensaje
      - version
      - timestamp
      title: PingRespuesta
